"""Added some files at the momemnt

Revision ID: 26f8faadd7c4
Revises: 9fec249837f2
Create Date: 2025-11-17 17:54:39.357870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26f8faadd7c4'
down_revision: Union[str, None] = '9fec249837f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completion_stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('divided_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_file_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_file_id'], ['projectfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_file_id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['project_file_id'], ['projectfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlightrect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('element_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('user', 'password_hash')
    op.drop_table('highlightrect')
    op.drop_table('comment')
    op.drop_table('highlight')
    op.drop_table('projectfile')
    op.drop_table('project')
    # ### end Alembic commands ###
