"""Delete child comments when root comment deleted

Revision ID: 4e49af3f4bf4
Revises: aa32b7c541e8
Create Date: 2025-12-01 22:56:52.904079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e49af3f4bf4'
down_revision: Union[str, None] = 'aa32b7c541e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.String(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint('comments_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('comments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'highlights', ['highlight_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('deleted')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('project_file_id')

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.alter_column('memo',
               existing_type=sa.String(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
        batch_op.add_column(sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('filename')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('project_name')

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('file_size')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('memo',
               existing_type=sa.Text(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_file_id', sa.Integer(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_ibfk_1', 'highlights', ['highlight_id'], ['id'])
        batch_op.create_foreign_key('comments_ibfk_2', 'comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key('comments_ibfk_3', 'project_files', ['project_file_id'], ['id'])
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
