"""Added stage column to projects table

Revision ID: 7a500d26f8ce
Revises: 8a2f8b1f6a48
Create Date: 2025-11-19 23:29:13.952085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a500d26f8ce'
down_revision: Union[str, None] = '8a2f8b1f6a48'  # 変更: aa32b7c541e8 → 8a2f8b1f6a48
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('stage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'stage')
    # ### end Alembic commands ###
