"""Changed project_files table

Revision ID: a52348852470
Revises: 7a500d26f8ce
Create Date: 2025-11-20 19:09:59.021902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a52348852470'
down_revision: Union[str, None] = '7a500d26f8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # カラムの存在確認をしてから削除
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('project_files')]
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.add_column('project_files', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    
    # カラムが存在する場合のみ削除
    if 's3_key' in columns:
        op.drop_column('project_files', 's3_key')
    if 's3_bucket' in columns:
        op.drop_column('project_files', 's3_bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('s3_bucket', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('project_files', sa.Column('s3_key', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('project_files', 'file_url')
    op.drop_column('project_files', 'file_key')
    # ### end Alembic commands ###
