"""Changed project_files table

Revision ID: a52348852470
Revises: 7a500d26f8ce
Create Date: 2025-11-20 19:09:59.021902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a52348852470'
down_revision: Union[str, None] = '7a500d26f8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.add_column('project_files', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('project_files', sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('project_files', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('project_files', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('project_files', 's3_bucket')
    op.drop_column('project_files', 'file_type')
    op.drop_column('project_files', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('s3_key', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('project_files', sa.Column('file_type', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('project_files', sa.Column('s3_bucket', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('project_files', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('project_files', 'updated_at')
    op.drop_column('project_files', 'mime_type')
    op.drop_column('project_files', 'file_url')
    op.drop_column('project_files', 'file_key')
    # ### end Alembic commands ###
