"""Fixed comments and highlights table

Revision ID: aa32b7c541e8
Revises: a52348852470
Create Date: 2025-11-23 01:54:54.087345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa32b7c541e8'
down_revision: Union[str, None] = 'a52348852470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_file_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('memo', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('text', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_file_id'], ['project_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('text', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('highlight_rects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('element_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_rects')
    op.drop_table('comments')
    op.drop_table('highlights')
    # ### end Alembic commands ###
