"""Added table for saving chunked text

Revision ID: adda7fb19530
Revises: 5a27366052c3
Create Date: 2026-01-01 07:37:19.575367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adda7fb19530'
down_revision: Union[str, None] = '5a27366052c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_formatted_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('formatted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_formatted_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_formatted_texts_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_formatted_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_formatted_texts_document_id'))

    op.drop_table('document_formatted_texts')
    # ### end Alembic commands ###
