"""Change projects table to documents table

Revision ID: c9682594a6ad
Revises: 4e49af3f4bf4
Create Date: 2025-12-08 09:09:17.612029

"""
from typing import Sequence, Union
import datetime

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9682594a6ad'
down_revision: Union[str, None] = '4e49af3f4bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # highlightsテーブルの外部キーを先に変更
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_file_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('highlights_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'document_files', ['document_file_id'], ['id'])
        batch_op.drop_column('project_file_id')
    
    # 外部キー制約を削除した後にテーブルを削除
    op.drop_table('project_files')
    op.drop_table('projects')

    # --- seed users (PostgreSQL) ---
    from app.core.security import get_password_hash

    now = datetime.datetime.utcnow()
    seed_users = [
        {
            "name": "Sample",
            "email": "test.test@test.com",
            "hashed_password": get_password_hash("Password1"),
            "deleted_at": None,
        },
        {
            "name": "Sample2",
            "email": "test2.test@test.com",
            "hashed_password": get_password_hash("Password2"),
            "deleted_at": None,
        },
        {
            "name": "Sample3",
            "email": "test3.test@test.com",
            "hashed_password": get_password_hash("Password3"),
            "deleted_at": None,  # 論理削除例が必要なら適宜値を設定
        },
    ]

    for u in seed_users:
        op.execute(
            sa.text(
                """
                INSERT INTO users (name, email, hashed_password, created_at, updated_at, deleted_at)
                VALUES (:name, :email, :hashed_password, :created_at, :updated_at, :deleted_at)
                ON CONFLICT (email) DO NOTHING
                """
            ),
            {
                "name": u["name"],
                "email": u["email"],
                "hashed_password": u["hashed_password"],
                "created_at": now,
                "updated_at": now,
                "deleted_at": u["deleted_at"],
            },
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # まず新しいテーブルを作成
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('stage', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='projects_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project_files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('file_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False),
    sa.Column('file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_files_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    # highlightsテーブルの外部キーを戻す
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_file_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        # 制約名を明示的に指定して削除
        batch_op.drop_constraint('highlights_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('highlights_ibfk_1', 'project_files', ['project_file_id'], ['id'])
        batch_op.drop_column('document_file_id')

    # --- delete seeded users ---
    op.execute(
        sa.text(
            """
            DELETE FROM users
            WHERE email IN (
                'test.test@test.com',
                'test2.test@test.com',
                'test3.test@test.com'
            )
            """
        )
    )

    # documentsテーブルを削除
    op.drop_table('document_files')
    op.drop_table('documents')
    # ### end Alembic commands ###
