"""Change table design

Revision ID: d8dc816adbb8
Revises: 8a2f8b1f6a48
Create Date: 2025-11-19 23:20:20.011632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8dc816adbb8'
down_revision: Union[str, None] = '8a2f8b1f6a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('comments_ibfk_3'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'deleted')
    op.drop_column('comments', 'edited_at')
    op.drop_column('comments', 'project_file_id')
    op.add_column('project_files', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project_files', sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project_files', sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('project_files', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('project_files', 'filename')
    op.add_column('projects', sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'project_name')
    op.add_column('project_files', sa.Column('filename', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('project_files', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('project_files', 'file_size')
    op.drop_column('project_files', 's3_bucket')
    op.drop_column('project_files', 's3_key')
    op.drop_column('project_files', 'file_name')
    op.add_column('comments', sa.Column('project_file_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('edited_at', mysql.DATETIME(), nullable=True))
    op.add_column('comments', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_ibfk_3'), 'comments', 'project_files', ['project_file_id'], ['id'])
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
